polygon_pos_package:
  participants:
    - kind: validator
      cl_type: heimdall-v2
      cl_image: 0xpolygon/heimdall-v2:0.4.0
      el_type: bor
      el_image: 0xpolygon/bor:2.3.0
      count: 4
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: 0xpolygon/heimdall-v2:0.4.0
      el_type: bor
      el_image: 0xpolygon/bor:2.3.0
      count: 2
  setup_images:
    validator_config_generator: europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/public/pos-validator-config-generator:0.4.0
