[default]
extend-ignore-re = [
  "\".*=\",", # cometbft private keys
]

[files]
extend-exclude = [
  "static_files/additional_services/grafana/dashboards/bor.json",
  "static_files/additional_services/grafana/dashboards/heimdall.json",
]
