{
 "title": "Panoptichain",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   { "name": "provider", "query": { "query": "label_values(provider)" } }
  ]
 },
 "panels": [
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_height{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Blocks Observed",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_block{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gas Used (million gas)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Base Fee Per Gas (gwei)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_base_fee_per_gas{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Gas Limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_gas_limit{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Block Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_difficulty{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_block_size{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uncles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_uncles{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions Per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transactions Per Block",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(le) (panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Transaction Value (ETH)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Gas Tip Cap (gwei)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Gas Price (gwei)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Gas Limit (gas)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Cost (ETH)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Time to Mine",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_time_to_mine_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_time_to_mine_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_time_to_mine_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  },
  {
   "title": "Panoptichain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panoptichain Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_system_uptime)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Refresh State Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_system_refresh_state_time_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_system_refresh_state_time_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_system_refresh_state_time_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  }
 ]
}