# Port identifiers and numbers.
RPC_PORT_ID = "rpc"
RPC_PORT_NUMBER = 8545

WS_PORT_ID = "ws"
WS_PORT_NUMBER = 8546

DISCOVERY_PORT_ID = "discovery"
DISCOVERY_PORT_NUMBER = 30303

METRICS_PORT_ID = "metrics"
METRICS_PORT_NUMBER = 7071
