#!/usr/bin/env python3
"""
Render matrix.json into the version matrix documentation page.

Produces docs/docs/version-matrix.md: one table for the container
images we deploy, one for the external Kurtosis packages we pin, each with a
status indicator and links to the deployed and latest upstream versions.
"""

import json
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Optional

STATUS_EMOJI = {
    "matches stable": "✅",
    "newer than stable": "⚡️",
    "behind stable": "🚨",
    "pinned": "📌",
    "tracking head": "⚠️",
}

REPO_URL = "https://github.com/0xPolygon/kurtosis-pos"


class MarkdownMatrixGenerator:
    """Generates the Markdown version matrix from extracted data."""

    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self.matrix_json_path = repo_root / "scripts" / "version-matrix" / "matrix.json"
        self.output_path = repo_root / "docs" / "docs" / "version-matrix.md"

    def load_matrix_data(self) -> Dict:
        if not self.matrix_json_path.exists():
            raise FileNotFoundError(
                f"Matrix data not found at {self.matrix_json_path}. "
                f"Run extract-versions.py first.")
        return json.loads(self.matrix_json_path.read_text())

    def generate_markdown_report(self, data: Dict) -> str:
        # Sits between Guides (3) and Appendix (5), matching kurtosis-cdk where
        # the matrix is a top-level section rather than an appendix entry.
        md = "---\nsidebar_position: 4\n---\n\n"
        md += "# Version Matrix\n\n"
        md += "> This page is generated by `scripts/version-matrix`. Do not edit it by hand.\n\n"
        md += "Versions of every component the package deploys, compared against "
        md += "the latest upstream release.\n\n"

        md += "## Status\n\n"
        md += "| Status | Meaning |\n"
        md += "| ------ | ------- |\n"
        md += "| ✅ matches stable | Running the latest upstream release. |\n"
        md += "| ⚡️ newer than stable | Ahead of the latest release — a prerelease or a patched build. |\n"
        md += "| 🚨 behind stable | An upstream release is available and should be picked up. |\n"
        md += "| 📌 pinned | Deliberately held back — the reason is shown inline. |\n"
        md += "| ⚠️ tracking head | Head-tracked package drifting from upstream, but not yet stale. |\n\n"

        md += "## Images\n\n"
        md += "Container images deployed by the package, pinned in "
        md += f"[`src/config/constants.star`]({REPO_URL}/blob/main/src/config/constants.star).\n\n"
        md += self._generate_image_table(data.get("images", {}))

        md += "\n### Untracked images\n\n"
        md += "Some images are deliberately absent from the table above: the "
        md += f"`pos-*` images are [built in this repo]({REPO_URL}/tree/main/docker) "
        md += "and published by `publish-images.yaml`, and `toolbox` / "
        md += "`ethstats-server` live on Artifact Registry. Neither has an "
        md += "upstream release stream to compare against. The full list is "
        md += "`SKIPPED_IMAGES` in `scripts/version-matrix/extract-versions.py`.\n"

        packages = data.get("packages", {})
        if packages:
            md += "\n## Kurtosis packages\n\n"
            md += "External Kurtosis packages the package depends on. Versions are pinned "
            md += f"in the [`replace` block of `kurtosis.yml`]({REPO_URL}/blob/main/kurtosis.yml), "
            md += "which is the single place to bump them.\n\n"
            md += self._generate_package_table(packages)

        return md

    def _generate_image_table(self, images: Dict) -> str:
        table = "| Component | Deployed version | Latest stable version | Status |\n"
        table += "| --------- | ---------------- | --------------------- | ------ |\n"

        for name, component in sorted(images.items()):
            version = component.get("version")
            latest_version = component.get("latest_version")

            table += (
                f"| {name}"
                f" | {self._link(version, component.get('version_source_url'))}"
                f" | {self._link(latest_version, component.get('latest_version_source_url'))}"
                f" | {self._status(component.get('status'), pin_reason=component.get('pin_reason'))} |\n"
            )
        return table

    def _generate_package_table(self, packages: Dict) -> str:
        table = "| Package | Pinned version | Latest stable version | Status |\n"
        table += "| ------- | -------------- | --------------------- | ------ |\n"

        for name, package in sorted(packages.items()):
            pin = package.get("pin")
            latest_version = package.get("latest_version")

            # Commit pins are shortened to keep the column narrow; the status
            # column already reports how far a pin has drifted.
            pin_label = pin[:12] if pin and len(pin) > 12 else pin

            # Head-tracked packages release too rarely for a tag to be a useful
            # baseline, so the comparison point is the branch tip. Say so rather
            # than presenting a bare sha as a "stable version".
            latest_label = latest_version
            if latest_version and package.get("tracking_mode") == "head":
                latest_label = f"HEAD ({latest_version})"

            table += (
                f"| [{name}](https://{name})"
                f" | {self._link(pin_label, package.get('pin_source_url'))}"
                f" | {self._link(latest_label, package.get('latest_version_source_url'))}"
                f" | {self._status(package.get('status'), package.get('commit_distance'), package.get('pin_reason'))} |\n"
            )
        return table

    @staticmethod
    def _link(label: Optional[str], url: Optional[str]) -> str:
        """Render a version as a link to its release, or plain if unknown."""
        if not label:
            return "N/A"
        return f"[{label}]({url})" if url else label

    @staticmethod
    def _status(status: Optional[str], commit_distance: Optional[str] = None,
                pin_reason: Optional[str] = None) -> str:
        """Render a status with its emoji, drift distance and pin reason."""
        if not status:
            return "N/A"

        display = f"{STATUS_EMOJI.get(status, '❓')} {status}"
        if commit_distance:
            display += f" — {commit_distance}"
        if pin_reason:
            display += f" — {pin_reason}"
        return display


def format_with_rumdl(path: Path) -> None:
    """Align the generated tables with `rumdl fmt`.

    The repo lints markdown with MD060 (aligned tables), which pads cells to
    their unicode display width — and the status emojis do not all have the same
    width (✅ is 2 columns, ⚡️ is 1 plus a zero-width variation selector).
    Rather than reimplement that padding and risk drifting from the linter, let
    the linter itself be the source of truth: without this, every generated page
    would fail `rumdl check` and the nightly diff would never be empty.
    """
    if not shutil.which("rumdl"):
        print("Warning: rumdl not found, leaving tables unaligned. "
              "Install it (https://github.com/rvben/rumdl) or run "
              "`rumdl fmt` on the generated page before committing.")
        return

    result = subprocess.run(["rumdl", "fmt", str(path)],
                            capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Warning: `rumdl fmt` failed: {result.stderr.strip()}")


def main():
    repo_root = Path(__file__).parent.parent.parent
    generator = MarkdownMatrixGenerator(repo_root)

    print("Loading matrix data...")
    data = generator.load_matrix_data()

    print("Generating Markdown content...")
    content = generator.generate_markdown_report(data)

    generator.output_path.write_text(content)
    format_with_rumdl(generator.output_path)
    print(f"Version matrix saved to {generator.output_path}")


if __name__ == "__main__":
    main()
