name: run-e2e-tests
description: Run end-to-end pos tests

inputs:
  pos_e2e_tag:
    description: The git tag, branch, or commit hash of 0xPolygon/pos-e2e
    required: false
    default: c439c414716b9df098503d5a1e385f0829860f6c
  pos_e2e_token:
    description: GitHub token with read access to 0xPolygon/pos-e2e
    required: true
  polygon_cli_version:
    description: The release version of polygon-cli
    required: false
    default: v0.1.109

runs:
  using: composite
  steps:
    - name: Clone 0xPolygon/pos-e2e
      uses: actions/checkout@v6
      with:
        repository: 0xPolygon/pos-e2e
        path: pos-e2e
        ref: ${{ inputs.pos_e2e_tag }}
        token: ${{ inputs.pos_e2e_token }}

    - name: Install bats
      uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        detik-path: ${{ github.workspace }}/lib/bats-detik
        file-path: ${{ github.workspace }}/lib/bats-file

    - name: Install polygon-cli
      shell: bash
      run: |
        pushd $(mktemp -d) || exit 1
        curl -s -L "https://github.com/0xPolygon/polygon-cli/releases/download/${{ inputs.polygon_cli_version }}/polycli_${{ inputs.polygon_cli_version }}_linux_amd64.tar.gz" > polycli.tar.gz
        tar xf polycli.tar.gz
        sudo mv polycli_* /usr/local/bin/polycli
        polycli version
        popd

    - name: Run bridge tests
      working-directory: pos-e2e
      shell: bash
      run: |
        bats --filter-tags bridge tests/bridge/plasma.bats tests/bridge/pos.bats
        bats --filter-tags withdraw tests/bridge/plasma.bats tests/bridge/pos.bats
      env:
        TIMEOUT_SECONDS: 600 # default: 180

    - name: Run validator tests
      working-directory: pos-e2e
      shell: bash
      run: bats tests/heimdall/stake/validator.bats
      env:
        TIMEOUT_SECONDS: 600 # default: 180
