name: kurtosis-pre-run
description: Prepare the environment for deploying Kurtosis packages

inputs:
  docker_username:
    description: The username for docker registry
    required: false
  docker_token:
    description: The token for docker registry
    required: false

runs:
  using: composite
  steps:
    # Release disk space
    - name: Free up disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true

    # Install dependencies
    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install -y kurtosis-cli=1.12.1
        kurtosis analytics disable
        kurtosis version

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@50d5a8956f2e319df19e6b57539d7e2acb9f8c1e # v1.5.0
      with:
        version: v1.4.2
        cache: false

    # Load cached images
    - name: Cache docker images
      id: cache-docker
      uses: actions/cache@v4
      with:
        path: /tmp/docker-images
        key: docker-images-${{ github.run_id }}
        restore-keys: |
          docker-images-

    - name: Load cached docker images
      shell: bash
      run: |
        echo "Loading cached Docker images..."
        if [ -d "/tmp/docker-images" ]; then
          for image_tar in /tmp/docker-images/*.tar; do
            if [ -f "$image_tar" ]; then
              {
                docker load -i "$image_tar"
              } &
            fi
          done
          wait
          echo "Cached images loaded successfully"
        else
          echo "No cached images found, will pull from GCR"
        fi
        docker images

    # Login to registries
    - name: Login to docker registry
      if: ${{ inputs.docker_username && inputs.docker_token }}
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Login to github container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
