name: monitor
description: Monitor blockchain progress (blocks, milestones, checkpoints, spans, validators)

inputs:
  docker_network:
    description: Docker network name
    required: false
    default: kt-pos
  skip_milestones:
    description: Skip milestone monitoring
    required: false
    default: 'false'
  skip_checkpoints:
    description: Skip checkpoint monitoring
    required: false
    default: 'false'
  skip_spans:
    description: Skip span monitoring
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: List containers
      shell: bash
      run: docker ps --filter "network=${{ inputs.docker_network }}" --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"

    - name: Monitor Bor block progress
      working-directory: .github/actions/monitor
      shell: bash
      run: ./blocks-bor.sh ${{ inputs.enclave_name }}

    - name: Monitor Heimdall block progress
      working-directory: .github/actions/monitor
      shell: bash
      run: ./blocks-heimdall.sh ${{ inputs.enclave_name }}

    - name: Monitor span progress
      if: inputs.skip_spans != 'true'
      working-directory: .github/actions/monitor
      shell: bash
      run: ./spans.sh ${{ inputs.enclave_name }}

    - name: Monitor milestone progress
      if: inputs.skip_milestones != 'true'
      working-directory: .github/actions/monitor
      shell: bash
      run: ./milestones.sh ${{ inputs.docker_network }}

    - name: Monitor checkpoint progress
      if: inputs.skip_checkpoints != 'true'
      working-directory: .github/actions/monitor
      shell: bash
      run: ./checkpoints.sh ${{ inputs.docker_network }}
