name: test-state-sync
description: Test state sync functionality

inputs:
  enclave_name:
    description: The name of the kurtosis enclave
    required: false
    default: pos
  l1_rpc:
    description: The RPC URL for the L1 node
    required: false
    default: el-1-geth-lighthouse
  agglayer_e2e_tag:
    description: The git tag, branch, or commit hash of agglayer/e2e
    required: false
    default: 2687c0c751e7cae2deaf4e99b13ae0d0ef97b2d7

runs:
  using: composite
  steps:
    - name: Clone agglayer/e2e
      uses: actions/checkout@v6
      with:
        repository: agglayer/e2e
        path: agglayer-e2e
        ref: ${{ inputs.agglayer_e2e_tag }}

    - name: Install bats
      uses: bats-core/bats-action@42fcc8700f773c075a16a90eb11674c0318ad507 # 3.0.1
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        detik-path: ${{ github.workspace }}/lib/bats-detik
        file-path: ${{ github.workspace }}/lib/bats-file

    - name: Determine L1 RPC URL
      shell: bash
      run: |
        if [[ "${{ inputs.l1_rpc }}" == "el-1-geth-lighthouse" ]]; then
          l1_rpc_url="http://$(kurtosis port print ${{ inputs.enclave_name }} el-1-geth-lighthouse rpc)"
        else
          l1_rpc_url="$(kurtosis port print ${{ inputs.enclave_name }} ${{ inputs.l1_rpc }} rpc)"
        fi
        echo "L1_RPC_URL=$l1_rpc_url" >> $GITHUB_ENV
        echo "l1_rpc_url=$l1_rpc_url"

    - name: Test state syncs
      working-directory: agglayer-e2e
      shell: bash
      run: bats --filter 'bridge MATIC/POL, ERC20, and ERC721 from L1 to L2 and confirm L2 balances increased' tests/pos/bridge.bats
      env:
        L1_RPC_URL: ${{ env.L1_RPC_URL }}
        TIMEOUT_SECONDS: 600 # default: 180
