name: publish-snapshots

# Workflow to build and publish snapshots to GHCR.
on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to test the workflow
        required: false
        default: vx.y.z-test

concurrency:
  group: publish-snapshots
  cancel-in-progress: false

env:
  ENCLAVE_NAME: pos

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        include:
          - image_name: 0xpolygon/pos-devnet-small
          - image_name: 0xpolygon/pos-devnet-large
            extra_flags: --args-file .github/configs/large.yml.norun

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy devnet
        run: kurtosis run --enclave=${{ env.ENCLAVE_NAME }} ${{ matrix.extra_flags }} .

      - name: Create snapshot
        run: ./scripts/snapshot/snapshot.sh ${{ env.ENCLAVE_NAME }}

      - name: Get tag
        run: echo "TAG=${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}" >> $GITHUB_ENV

      - name: Push snapshot image
        run: |
          full_image="ghcr.io/${{ matrix.image_name }}:${{ env.TAG }}"
          docker tag pos-devnet "$full_image"
          docker push "$full_image"
