name: snapshot

on:
  schedule:
    - cron: 0 6 * * * # Run this workflow every day at 6 AM Paris time (UTC).
  workflow_dispatch:

# Permissions required to pull images from GAR
permissions:
  contents: read
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  ENCLAVE_NAME: pos

jobs:
  snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy devnet
        run: kurtosis run --enclave=${{ env.ENCLAVE_NAME }} --args-file=.github/configs/large.yml.norun .

      - name: Create snapshot
        run: ./scripts/snapshot/snapshot.sh ${{ env.ENCLAVE_NAME }}

      - name: Remove the kurtosis enclave
        run: kurtosis enclave rm --force ${{ env.ENCLAVE_NAME }}

      - name: Extract snapshot data
        run: ./scripts/snapshot/extract.sh pos-devnet

      - name: Restore devnet from snapshot
        run: ./scripts/snapshot/restore.sh

      - name: List containers
        run: docker ps --filter "network=kt-${{ env.ENCLAVE_NAME }}" --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"

      - name: Monitor Bor block progress
        working-directory: .github/actions/monitor
        run: ./blocks-bor.sh kt-${{ env.ENCLAVE_NAME }} 356 # 100 blocks after the snapshot block

      - name: Monitor Heimdall block progress
        working-directory: .github/actions/monitor
        run: ./blocks-heimdall.sh kt-${{ env.ENCLAVE_NAME }} 100
